name: Secure API Key

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call API using GitHub secret
        run: |
          echo "Calling API with secret..."
          curl "https://api.openweathermap.org/data/2.5/weather?q=Toronto&appid=${{ secrets.OPENWEATHER_API_KEY }}"
