name: Secret API Key

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script with secret key
        run: |
          echo "Calling API with secret..."
          curl "https://api.solar.com/data?apikey=${{ secrets.API_KEY }}"
