name: Secure API Key with Secrets

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script using secret API key
        run: |
          echo "Calling API with secret key..."
          curl "https://api.openweathermap.org/data/2.5/weather?q=Toronto&appid=${{ secrets.OPENWEATHER_API_KEY }}"
